server:
  port: 8000
  servlet:
    context-path: /file-api

## Database Properties
spring:
  jackson:
    serialization:      fail-on-empty-beans: false
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/file_structure?allowPublicKeyRetrieval=true&useSSL=false&useTimezone=true&serverTimezone=UTC
    username: root
    password: 12345
    
## Hibernate Properties
# The SQL dialect makes Hibernate generate better SQL for the chosen database
#pring.jpa.database-platform=org.hibernate.dialect.Oracle10gDialec
  jpa:
# Hibernate ddl auto (create, create-drop, validate, update)
    hibernate:
      ddl-auto: create-drop
origin-allowed-front: http://localhost:8081       
